### ISSUE TITLE
METATHEOREM: Run Theorem 3.8 against the list of unresolved implications

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#175]
Run Theorem 3.8 against the latest file available in #173 to see if any additional anti-implications can be generated.  If so, store them as a list of `conjecture`s (if #131 is not yet completed) or `theorem`s (if #131 is completed) to add to the repository.

**Comment by Shiney** [comment]
I may have missed something about the current efforts to use magma search to find anti implcations so possibly still worth dojng this, but wouldn't any of these also (already?) get found if we just use the cyclic group of Z/6 as the magma (because each side of the equation can have at most 5 variables in, so if you equation with unbalanced numbers of variables wlog "y" then if you set all the variables except y to 0 and y to 1 then you'll get the counter example)

**Comment by teorth** [comment]
This is a good point, and we should instead start collecting interesting medium sized magmas to run.  So I am closing this issue and opening #180 instead.
