### ISSUE TITLE
FRONTEND: Use CI to auto-generate a Hasse diagram of the equations in Equations.lean, and display this image in README.md and blueprint

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#183]
Ideally, the image should be stored in some static location (presumably in the Images folder), and README.md and Figure 3.1 of the blueprint can point to that location (and the old manually-constructed Hasse diagram can be dropped from the blueprint as being obsolete).  NOTE: the Hasse diagram should be oriented according to the updated guidance at CONTRIBUTING.md

**Comment by carlini** [comment]
Something to think about: if the (4696^2) image is re-generated on every change to the number of equations, this is going to cause an extra ~200k of data to be added to the git repo every time. Since these images never go away when they're replaced on the next commit, this repository might start to get somewhat unwieldy after a few hundred changes to the repo.

Maybe this isn't too big of a concern? 20MB of data isn't that much. But I guess what I'm saying is: it would be prudent to think carefully if this there are going to be multiple large data files being added each time the state changes.

An alternate approach could be to have the CI tool just set the image aside somewhere else, in which case the image would go away after each commit. So if someone in the future wanted to look back at the past, they'd have to re-generate the images, in which case this should be made easy to do.

Not sure what the best thing to do is, but it's worth a bit of thought.

**Comment by teorth** [comment]
Hmm. Perhaps the image should only be generated on a daily basis?

**Comment by teorth** [comment]
Obviously this task should be integrated with the new dashboard https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/proposal.3A.20add.20a.20dashboard.20page.20to.20the.20website

**Comment by goens** [comment]
@carlini Note that the Equations in `Equations.lean` are just the 37 ones from subgraph, so it's 37^2, and not sure there's that many more changes coming for this, so I wouldn't worry about it for this case.

**Comment by carlini** [comment]
Oh, my mistake I thought the intent was to do it for them all. In which case that's obviously fine!

**Comment by vlad902** [comment]
claim

I already have the `generate_graphviz_graph.rb` tool, let's see how painful it is to get it to output a decent-looking Hesse diagram.

**Comment by vlad902** [comment]
claim

**Comment by vlad902** [comment]
I was working on something that looked more Hasse-like, but then I thought to look at the Subgraph, and at least with the implications from #281 (maybe before as well, I didn't think to look), no elements in the Subgraph have any outstanding unknowns with the other elements in the Subgraph. (Generally, of those, only Equation 168 has remaining unknowns left with non-Subgraph nodes.) So is it worth going through the trouble of re-generating it through CI if it's staying the same?

**Comment by vlad902** [comment]
![subgraph](https://github.com/user-attachments/assets/d955048a-dcee-47d0-afca-e5602c160c8e)

**Comment by teorth** [comment]
Nice!  Well, if it's already done, we can mark that as an early success, and just have a static image (say in the images directory, and have it as a display image in the front page.  I think it does a good job of conveying what our project is trying to accomplish).

**Comment by vlad902** [comment]
propose PR #305
