### ISSUE TITLE
METATHEOREM: Non-implication proofs using invariants

### ISSUE THREAD

**Issue by 0art0** [teorth/equational_theories#377]
Generating conjectures and proofs of non-implications using invariants generated from lifting magma families, following [Chapter 8 of the blueprint](https://teorth.github.io/equational_theories/blueprint/sect0007.html).

**Comment by 0art0** [comment]
claim

**Comment by Shreyas4991** [comment]
Hey, this might be a bug in our CI setup, so we will fix this. Thanks for triggering it. 

Basically only maintainers (mostly only Terence Tao) ought to make project tasks. Before claiming an issue, please discuss it on a zulip thread and link it in the issue. Once one of our maintainers agrees and the issue is converted to a project task, and then you can claim it. The bug here is that when you commented "claim" the CI didn't check whether this issue was already a project task.

I am very sorry I am being so insistent on what must sound like bureaucratic processes, especially since we are responsible for the CI bug in this instance. We will fix this on our end ASAP. Apologies again.

**Comment by Shreyas4991** [comment]
In this case, since the mistake is on our end, we will let this issue be on the dashboard.

**Comment by teorth** [comment]
Actually I manually added it to the project as it looked appropriate.  I should probably have left a notification, will do so in the future.

**Comment by pitmonticone** [comment]
Great @teorth, thanks!

**Comment by Shreyas4991** [comment]
Oh okay. One way to add these issues to the project dashboard is to add the `project-task` label to it. Then the CI will automatically add it to the dashboard. Since only maintainers can currently add this label, we will know that this was added by a maintainer (in this case you). 

Also, @0art0 , more apologies from me for this confusion.

**Comment by 0art0** [comment]
Thanks for clarifying the rules, and I apologize for not properly adhering to the contribution guidelines yet again.

**Comment by 0art0** [comment]
propose #389

**Comment by 0art0** [comment]
I would soon like to open another issue for producing proofs of these claims.

**Comment by 0art0** [comment]
awaiting-review

**Comment by Shreyas4991** [comment]
propose PR #389

**Comment by 0art0** [comment]
withdraw PR #389

**Comment by 0art0** [comment]
propose PR #526
