### ISSUE TITLE
Investigate transitively reducing the current set of implications on main

### ISSUE THREAD

**Issue by vlad902** [teorth/equational_theories#493]
Currently, about 2/3rd of implications on main are "vestigial" (e.g. no longer in the transitive reduction.) It would be good to see how much removing them 1) improves build times, and 2) improves graph operation times, e.g. generating the extract_implications --closure.

**Comment by teorth** [comment]
This is a good idea, and I've added it as a project task, but just wanted to make one comment for posterity: when we write the paper and review the performance of various automated implication tactics, we may need to run these tactics on the whole implication set from scratch to obtain the required metrics, rather than rely on whatever the state of the reduced implication set is at the time of the paper writing process, because these pruning procedures could severely undercount the performance of any given tactic.

**Comment by vlad902** [comment]
Yes, and this is already actually the case, since e.g. the vampire run was pruned to avoid overlap with the elements already in transitive closure as it was at the time it was committed, so every step has already had reduction applied relative to what came before it (except for perhaps some of the very first commits.)

**Comment by vlad902** [comment]
claim

**Comment by vlad902** [comment]
propose PR #500
