### ISSUE TITLE
BLUEPRINT: Unify the Asterix and Greedy chapters into a combined chapter on infinite magma constructions

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#591]
See [this discussion](https://leanprover.zulipchat.com/#narrow/stream/458659-Equational/topic/1648.20!.3D.3E.20206/near/477014775) for a proposed sketch of the new chapter.

**Comment by zaklogician** [comment]
I had a bit of time and progressed this in #617. It should be merged once reviewed, but does not resolve this issue by itself.

**Why didn't I claim this?**

Because I have no time to work on it and won't for many weeks. But there's not much left: if you're reading this, I encourage you to claim it and take it up!

**What remains to be done?**

The survey of examples should be extended with a guide to a greedy argument. The surveyed examples are picked so that they are simple, but not trivial: the aim is not to showcase the most "powerful" applications of each technique, but to provide an accessible entrypoint for people who wish to study them. I think Pace Nielsen's greedy argument for 1701->3  is particularly good for this, but that should be done once #506 is merged (it's not clear until then whether to explain the final proof or [the original](https://leanprover.zulipchat.com/user_uploads/3121/psM1eYv4Yn1s1e3d5v1ZB0wt/NonImplication-updated.tex)). 

If by that point [this list](https://leanprover.zulipchat.com/#narrow/channel/458659-Equational/topic/Ways.20to.20analyze.20a.20given.20equation) will have expanded with important new techniques specifically for infinite magmas, a stub can be created for examples as well.
