### ISSUE TITLE
OEIS: Compute (and find a formula for) the number of equations involving n operations for small values of n (up to symmetry and relabeling), and submit to OEIS

### ISSUE THREAD

**Issue by teorth** [teorth/equational_theories#80]

**Comment by amirlb** [comment]
For reference, the values for n=0..6 are: 2, 5, 39, 364, 4284, 57882, 888365

**Comment by teorth** [comment]
Do you have code (e.g., on the main repo) that one can link to that can generate this?  That should be enough material for me to make a submission to OEIS.

**Comment by FLDutchmann** [comment]
For odd $n$, these appear to be $C_{n+1} B_{n+2}/2$, where $C_n$ is the $n$ th catalan number and $B_{n}$ the $n$ th Bell number. It's also very close for the even case, but there is some trouble for equations with an equal number of operations on both sides.

**Comment by FLDutchmann** [comment]
The idea: Pick a binary tree with $n+1$ nodes. The root will represent the equals sign, the rest a binary operation. There are $C_{n+1}$ of these. Then pick a rhyme scheme to label the variables. There are $B_{n+2}$ rhyme schemes on the $n+2$ variables. This process overcounts the equations by a factor of 2 (for odd $n$), because half the equations produced will have more variables on the LHS than the RHS.

**Comment by amirlb** [comment]
> Do you have code (e.g., on the main repo) that one can link to that can generate this? That should be enough material for me to make a submission to OEIS.

I ran the equation generation script after changing the size threshold to 6 and looked at the resulting file... Maybe we can just link to it? But I guess that within a few hours we'll have a combinatorial argument and won't need the code that generates the list for the submission.

**Comment by teorth** [comment]
I think for a typical OEIS submission, some code and a mathematical formula would both be appreciated.  We have code (in link for at least), but it looks like with a bit of effort we could also get an explicit math formula (which could then come with efficient code in e.g., SAGE, to calculate it).  The one tricky thing in getting an exact formula is how to account for laws such as `x ∘ x = y ∘ y` that are equal to their own reflection and so should not be divided by two in the final count, but presumably this can be worked out.  If someone is able to provide a formula (and it agrees with the numerical data) then I will submit all of this to the OEIS.

**Comment by amirlb** [comment]
Another thing we need to account for when calculating in the even case is that we exclude laws of the form E = E. That's of course just Ck Bk+1 more laws for n=2k.

When including these laws too the counts are 2, 5, 41, 364, 4294, 57882, 888440

**Comment by teorth** [comment]
Neither sequence seems to be in the OEIS, so we can submit both

**Comment by Command-Master** [comment]
For $n = 2k$ we have $((C_{2k+1} - C_k^2) B_{2k+2}) / 2$ laws with different number of operations in both sides, $(C_k choose 2) * B_{2k + 2}$ laws with different shapes, but for equal shapes and different names we need the to count rhyme schemes modulo reversal on $2k+2$ elements, and I'm unsure about that. The sequence of those starts with $0, 4, 86, 1988, 57488$ if I'm calculating correctly

**Comment by Command-Master** [comment]
For every rhyme scheme which is fixed by swapping both sides we have the partition restricted to the first half and the second half must be equal, and if we have $i$ sets on each restriction there are $\left{ \stack{k}{i} \right}$ (Stirgling number of the second kind) possibilities for that. Now for swapping both sides to fix the permutation then the links between the sets on each side must form an involution where they exist, and we can count that by $\sum_{j=0}^{\lfloor i/2 \rfloor} T(i, j) 2^{i - 2j} = \sum_{j=0}^{\lfloor i/2 \rfloor} \frac{i!}{j! (i-2j)!} 2^{i - 3j}$ where $T$ is [A100861](https://oeis.org/A100861), the number of matchings in a complete graph.
In total we get $D_{2k} = \frac{B_{2k}}2 + \frac{\sum_{i=0}^{k} \left{ \stack{k}{i} \right} \sum_{j=0}^{\lfloor i/2 \rfloor} \frac{i!}{j! (i-2j)!} 2^{i - 3j}}2$

**Comment by Command-Master** [comment]
For every rhyme scheme which is fixed by swapping both sides we have the partition restricted to the first half and the second half must be equal, and if we have $i$ sets on each restriction there are $\left\\{ {k \atop i} \right\\}$ (Stirgling number of the second kind) possibilities for that. Now for swapping both sides to fix the permutation then the links between the sets on each side must form an involution where they exist, and we can count that by $\sum_{j=0}^{\lfloor i/2 \rfloor} T(i, j) 2^{i - 2j} = \sum_{j=0}^{\lfloor i/2 \rfloor} \frac{i!}{j! (i-2j)!} 2^{i - 3j}$ where $T$ is [A100861](https://oeis.org/A100861), the number of matchings in a complete graph.
In total we get $D_{2k} = \frac{B_{2k}}2 + \frac{\sum_{i=0}^{k} \left\\{ {k \atop i} \right\\} \sum_{j=0}^{\lfloor i/2 \rfloor} \frac{i!}{j! (i-2j)!} 2^{i - 3j}}2$, so for $n = 2k$ the number of equations is:
$((C_{2k+1} - C_k^2) B_{2k+2}) / 2 + \binom{C_k}2 B_{2k + 2} + C_k (\frac{B_{2k+2}}2 + \frac{\sum_{i=0}^{k+1} \left\\{ {{k+1} \atop i} \right\\} \sum_{j=0}^{\lfloor i/2 \rfloor} \frac{i!}{j! (i-2j)!} 2^{i - 3j}}2 - B_k)$

**Comment by Command-Master** [comment]
For every rhyme scheme which is fixed by swapping both sides we have the partition restricted to the first half and the second half must be equal, and if we have $i$ sets on each restriction there are $\left\\{ {k \atop i} \right\\}$ (Stirgling number of the second kind) possibilities for that. Now for swapping both sides to fix the permutation then the links between the sets on each side must form an involution where they exist, and we can count that by $\sum_{j=0}^{\lfloor i/2 \rfloor} T(i, j) 2^{i - 2j} = \sum_{j=0}^{\lfloor i/2 \rfloor} \frac{i!}{j! (i-2j)!} 2^{i - 3j}$ where $T$ is [A100861](https://oeis.org/A100861), the number of matchings in a complete graph.
In total we get $D_{2k} = \frac{B_{2k}}2 + \frac{\sum_{i=0}^{k} \left\\{ {k \atop i} \right\\} \sum_{j=0}^{\lfloor i/2 \rfloor} \frac{i!}{j! (i-2j)!} 2^{i - 3j}}2$, so for $n = 2k$ the number of equations is:
$((C_{2k+1} - C_k^2) B_{2k+2}) / 2 + \binom{C_k}2 B_{2k + 2} + C_k (\frac{B_{2k+2}}2 + \frac{\sum_{i=0}^{k+1} \left\\{ {{k+1} \atop i} \right\\} \sum_{j=0}^{\lfloor i/2 \rfloor} \frac{i!}{j! (i-2j)!} 2^{i - 3j}}2 - B_{k+1})$

Python code to calculate it:
```python
from sympy.functions.combinatorial.numbers import stirling, bell, catalan
from sympy.functions.combinatorial.factorials import binomial, factorial

def D_(k):
    return sum(stirling(k, i) * sum(
            factorial(i) * 2**i // (factorial(j) * factorial(i - 2*j) * 2 ** (3 * j))
            for j in range(i//2 + 1)
        ) for i in range(k+1))

def D(k):
    return (bell(2*k) + D_(k)) // 2

def calc(n):
    if n == 0:
        return 2
    if n % 2 == 1:
        return catalan(n + 1) * bell(n + 2) // 2
    k = n // 2
    return (catalan(n + 1) - catalan(k)**2) * bell(n + 2) / 2 + \
        binomial(catalan(k), 2) * bell(n + 2) + \
        catalan(k) * ( D(k+1) - bell(k+1) )

for n in range(10):
    print(calc(n))
```

**Comment by Command-Master** [comment]
These formulas could likely be used to produce more efficient ranking/unranking algorithm, although I'm not sure if there's use for that

**Comment by amirlb** [comment]
Found @Command-Master 's sequence in OEIS with the help of a friend.

If the symmetry is flipping the order and not swapping the halves, we can define it for odd size as well. And this appears as a sequence in OEIS already, in the language of colorings.

 2 , 11 , 117 , 2152 , 58487 = A103293(2n + 1)

**Comment by teorth** [comment]
I'm trying to reproduce the counts and I'm not seeing why 11 = A103293(4) is the number of partitions of [4] up to reversal, I can only count 7: 1234, 12 + 34, 13 + 24, 14 + 23, 1 + 23 + 4, 14 + 2 + 3, 1 + 2 + 3 + 4.  And this would line up with the fact that there are 41 length 4 laws up to relabeling and reversal (not eliminating x=x type laws) but C_5*B_6 = 75 laws up to relabeling alone, since 41 = (75 + 7)/2.  (By the way the sequence C_n * B_{n+1} is https://oeis.org/A289679).

**Comment by teorth** [comment]
Oh wait I understand my confusion now.  I was counting partitions that were symmetric, rather than partitions up to reversal.  My count of 7 is $2D_4 - B_4 = 2 * 11 - 15$, so it all checks out.

**Comment by teorth** [comment]
I've updated the blueprint at https://teorth.github.io/equational_theories/blueprint/sect0001.html with my attempt to summarize the above discussion.  I would be grateful if someone could review the text, and specifically whether the equations provided match the numerics.  If it all checks out then I think I can submit the sequences

2, 5, 41, 364, 4294, 57882, 888440, ...

(for equations up to relabeling and symmetry) and

2, 5, 39, 364, 4284, 57882, 888365, 

(for equations up to relabeling, symmetry, and triviality) to the OEIS.

**Comment by amirlb** [comment]
Went through the blueprint, and implemented the formulas exactly as written there and everything checks out.

(Except in an unrelated part - in def. 1.2 it says "X is precisely the set of words of order 1" which it's actually the words of order 0)

**Comment by teorth** [comment]
Ok, i will submit to oeis later today and then close this issue.

It is somewhat orthogonal to the main goals of the project, but since the counting lemmas are already in the blueprint, i think i will add some tasks to formalize them in Lean at some point (but we need a bit more of the API for equations and relabeling to be developed first).

**Comment by teorth** [comment]
First OEIS sequence submitted.  The second one will reference the first, so I will need to get the first one approved before submitting the second.

**Comment by teorth** [comment]
First OEIS sequence has appeared: https://oeis.org/A376620 .  Will now work on submitting the second.

**Comment by teorth** [comment]
The second sequence is now posted at https://oeis.org/A376640 , closing this issue.  Thanks for all the contributions!
